'use strict';

const POINTS={A:{x:75,y:225},B:{x:145,y:70},C:{x:365,y:70},D:{x:295,y:225}};
// タイプDも、読み取りやすい標準的な平行四辺形の形で統一する。
const GENERIC={A:{x:75,y:225},B:{x:145,y:70},C:{x:365,y:70},D:{x:295,y:225}};
const esc=value=>String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;');
const edgeNames={AB:['A','B'],BC:['B','C'],DC:['D','C'],AD:['A','D']};

function pointOn(v,toward,distance){const dx=toward.x-v.x,dy=toward.y-v.y,len=Math.hypot(dx,dy)||1;return{x:v.x+dx/len*distance,y:v.y+dy/len*distance};}
function edgePoint(points,side,ratio){const [a,b]=edgeNames[side],p=points[a],q=points[b];return{x:p.x+(q.x-p.x)*ratio,y:p.y+(q.y-p.y)*ratio};}
function outward(points,side){const [a,b]=edgeNames[side],p=points[a],q=points[b],m=edgePoint(points,side,.5),dx=q.x-p.x,dy=q.y-p.y,len=Math.hypot(dx,dy)||1;let n={x:-dy/len,y:dx/len};const center={x:(points.A.x+points.B.x+points.C.x+points.D.x)/4,y:(points.A.y+points.B.y+points.C.y+points.D.y)/4};if((m.x+n.x*20-center.x)**2+(m.y+n.y*20-center.y)**2<(m.x-n.x*20-center.x)**2+(m.y-n.y*20-center.y)**2)n={x:-n.x,y:-n.y};return n;}

function angleMark(vertexName,previousName,nextName,text,tone){const v=POINTS[vertexName],previous=POINTS[previousName],next=POINTS[nextName],radius=27,start=pointOn(v,previous,radius),end=pointOn(v,next,radius);const u1={x:(previous.x-v.x)/Math.hypot(previous.x-v.x,previous.y-v.y),y:(previous.y-v.y)/Math.hypot(previous.x-v.x,previous.y-v.y)},u2={x:(next.x-v.x)/Math.hypot(next.x-v.x,next.y-v.y),y:(next.y-v.y)/Math.hypot(next.x-v.x,next.y-v.y)};const sum={x:u1.x+u2.x,y:u1.y+u2.y},sumLength=Math.hypot(sum.x,sum.y)||1,label={x:v.x+sum.x/sumLength*50,y:v.y+sum.y/sumLength*50},sweep=(u1.x*u2.y-u1.y*u2.x)>0?1:0;return `<path class="arc-${tone}" d="M${start.x.toFixed(1)} ${start.y.toFixed(1)} A${radius} ${radius} 0 0 ${sweep} ${end.x.toFixed(1)} ${end.y.toFixed(1)}"/><text class="angle-${tone}" x="${label.x.toFixed(1)}" y="${label.y.toFixed(1)}">${esc(text)}</text>`;}

function sideArc(side,label,tone){const start=edgePoint(POINTS,side,0),end=edgePoint(POINTS,side,1),mid=edgePoint(POINTS,side,.5),n=outward(POINTS,side),bend={x:mid.x+n.x*24,y:mid.y+n.y*24},text={x:mid.x+n.x*40,y:mid.y+n.y*40};return `<path class="length-${tone}" d="M${start.x.toFixed(1)} ${start.y.toFixed(1)} Q${bend.x.toFixed(1)} ${bend.y.toFixed(1)} ${end.x.toFixed(1)} ${end.y.toFixed(1)}"/><text class="length-${tone}-text" x="${text.x.toFixed(1)}" y="${text.y.toFixed(1)}">${esc(label)}</text>`;}
function tick(side,count=1,color='blue',ratio=.5){const p=edgePoint(GENERIC,side,ratio),[a,b]=edgeNames[side],v={x:GENERIC[b].x-GENERIC[a].x,y:GENERIC[b].y-GENERIC[a].y},len=Math.hypot(v.x,v.y)||1,u={x:v.x/len,y:v.y/len},n={x:-u.y,y:u.x};let result='';for(let i=0;i<count;i++){const gap=(i-(count-1)/2)*9,c={x:p.x+u.x*gap,y:p.y+u.y*gap};result+=`<path class="condition-${color}" d="M${(c.x-n.x*6).toFixed(1)} ${(c.y-n.y*6).toFixed(1)} L${(c.x+n.x*6).toFixed(1)} ${(c.y+n.y*6).toFixed(1)}"/>`;}return result;}
function parallel(side,count=1){const p=edgePoint(GENERIC,side,.5),[a,b]=edgeNames[side],v={x:GENERIC[b].x-GENERIC[a].x,y:GENERIC[b].y-GENERIC[a].y},len=Math.hypot(v.x,v.y)||1,u={x:v.x/len,y:v.y/len},n={x:-u.y,y:u.x};let result='';for(let i=0;i<count;i++){const gap=(i-(count-1)/2)*11,c={x:p.x+u.x*gap,y:p.y+u.y*gap},left={x:c.x-u.x*5-n.x*6,y:c.y-u.y*5-n.y*6},tip={x:c.x+u.x*5,y:c.y+u.y*5},right={x:c.x-u.x*5+n.x*6,y:c.y-u.y*5+n.y*6};result+=`<path class="condition-blue" d="M${left.x.toFixed(1)} ${left.y.toFixed(1)} L${tip.x.toFixed(1)} ${tip.y.toFixed(1)} L${right.x.toFixed(1)} ${right.y.toFixed(1)}"/>`;}return result;}
function genericAngle(vertex,previous,next,count){const v=GENERIC[vertex],p=GENERIC[previous],n=GENERIC[next],r=20,start=pointOn(v,p,r),end=pointOn(v,n,r);const u1={x:(p.x-v.x)/Math.hypot(p.x-v.x,p.y-v.y),y:(p.y-v.y)/Math.hypot(p.x-v.x,p.y-v.y)},u2={x:(n.x-v.x)/Math.hypot(n.x-v.x,n.y-v.y),y:(n.y-v.y)/Math.hypot(n.x-v.x,n.y-v.y)},sweep=(u1.x*u2.y-u1.y*u2.x)>0?1:0;let result='';for(let i=0;i<count;i++){const rr=r+i*7,a=pointOn(v,p,rr),b=pointOn(v,n,rr);result+=`<path class="condition-blue" d="M${a.x.toFixed(1)} ${a.y.toFixed(1)} A${rr} ${rr} 0 0 ${sweep} ${b.x.toFixed(1)} ${b.y.toFixed(1)}"/>`;}return result;}
function segmentTick(points,from,to,ratio=.5,count=1,className='condition-blue'){const a=points[from],b=points[to],dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1,u={x:dx/len,y:dy/len},n={x:-u.y,y:u.x},m={x:a.x+dx*ratio,y:a.y+dy*ratio};let result='';for(let i=0;i<count;i++){const gap=(i-(count-1)/2)*8,c={x:m.x+u.x*gap,y:m.y+u.y*gap};result+=`<path class="${className}" d="M${(c.x-n.x*7).toFixed(1)} ${(c.y-n.y*7).toFixed(1)} L${(c.x+n.x*7).toFixed(1)} ${(c.y+n.y*7).toFixed(1)}"/>`;}return result;}
function diagonalCenter(points){return{x:(points.A.x+points.C.x)/2,y:(points.A.y+points.C.y)/2};}
function rightAngleAtDiagonalCenter(points,className='condition-blue'){const o=diagonalCenter(points),towardC=pointOn(o,points.C,12),towardD=pointOn(o,points.D,12),u={x:towardC.x-o.x,y:towardC.y-o.y},v={x:towardD.x-o.x,y:towardD.y-o.y},corner={x:o.x+u.x+v.x,y:o.y+u.y+v.y};return `<path class="${className}" d="M${towardC.x.toFixed(1)} ${towardC.y.toFixed(1)} L${corner.x.toFixed(1)} ${corner.y.toFixed(1)} L${towardD.x.toFixed(1)} ${towardD.y.toFixed(1)}"/>`;}
function genericDiagonals(){return diagonals(GENERIC);}

function renderDiagram(fig){if(fig.mode==='interactive')return interactiveTemplate(fig);const base=`<svg viewBox="0 0 440 300" role="img"><style>.l{stroke:#24324a;stroke-width:3;fill:none}.d{stroke:#94a3b8;stroke-width:2;stroke-dasharray:7 6}.v{font:900 18px Outfit,sans-serif;fill:#24324a}.arc-known,.length-known{stroke:#2563eb;stroke-width:3;fill:none}.arc-ask,.length-ask{stroke:#dc2626;stroke-width:3;fill:none}.angle-known,.angle-ask,.length-known-text,.length-ask-text{font:800 16px Outfit,sans-serif;text-anchor:middle;dominant-baseline:middle}.angle-known,.length-known-text{fill:#2563eb}.angle-ask,.length-ask-text{fill:#dc2626}.condition-blue{stroke:#2563eb;stroke-width:2.5;fill:none;stroke-linecap:round}.special-mark{stroke:#dc2626;stroke-width:3;fill:none}.special-text{font:800 16px Outfit,sans-serif;fill:#dc2626;text-anchor:middle}</style>`;return base+(fig.mode==='generic'?generic(fig.criterion):parallelogram(fig))+`</svg>`;}

function lockControls(){return `<button type="button" class="lab-lock" data-lock="angle" aria-pressed="false">🔓 角度をロック</button><button type="button" class="lab-lock" data-lock="length" aria-pressed="false">🔓 長さをロック</button>`;}
function interactiveTemplate(fig){return `<div class="special-lab-wrap"><div class="lab-toolbar" aria-label="図形の条件ロック">${lockControls()}</div><svg class="special-lab" viewBox="0 0 440 300" role="img" aria-label="頂点を動かして条件を満たす平行四辺形" data-target="${esc(fig.target)}">
  <text class="lab-help" x="220" y="18">問題の条件に合う平行四辺形に動かしてみよう！</text><text class="lab-subhelp" x="220" y="38">青い点B・Dをドラッグ（Cは連動）</text>
  <path class="lab-shape" data-shape/>
  <path class="lab-diagonal hidden" data-line="AC"/><path class="lab-diagonal hidden" data-line="BD"/>
  <path class="lab-condition hidden" data-marker="rightA"/><path class="lab-condition hidden" data-marker="sideAB"/><path class="lab-condition hidden" data-marker="sideBC"/>
  <path class="lab-condition hidden" data-marker="diagAC"/><path class="lab-condition hidden" data-marker="diagBD"/><path class="lab-condition hidden" data-marker="rightO"/>
  <circle class="lab-fixed" r="5" data-point="A"/><circle class="lab-derived" r="7" data-point="C"/>
  <g class="lab-handle" data-handle="B" role="slider" aria-label="頂点B"><circle class="lab-handle-hit" r="26"/><circle class="lab-handle-visual" r="13"/></g>
  <g class="lab-handle" data-handle="D" role="slider" aria-label="頂点D"><circle class="lab-handle-hit" r="26"/><circle class="lab-handle-visual" r="13"/></g>
  <text class="lab-vertex" data-label="A">A</text><text class="lab-vertex" data-label="B">B</text><text class="lab-vertex" data-label="C">C</text><text class="lab-vertex" data-label="D">D</text>
  <text class="lab-readout" x="220" y="267" data-readout></text><text class="lab-status" x="220" y="289" data-status>条件を作ろう</text>
</svg></div>`;}

function initSpecialInteraction(question,root){
  const svg=root.querySelector('.special-lab');if(!svg)return()=>{};
  const target=question.fig.target,A={x:95,y:220},points={B:{x:150,y:90},D:{x:285,y:220}},locks={angle:false,length:false,angleValue:null,angleSign:1,ab:null,bc:null};let active=null,activeId=null,stopped=false,boundaryHit=false;
  const $one=s=>svg.querySelector(s),shape=$one('[data-shape]'),status=$one('[data-status]'),readout=$one('[data-readout]');
  const diagonals=['equalDiag','perpDiag','squareDiag'].includes(target);
  const dist=(p,q)=>Math.hypot(q.x-p.x,q.y-p.y),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const vertexBox={minX:35,maxX:400,minY:50,maxY:275},derivedBox={minX:35,maxX:415,minY:50,maxY:285};
  const unit=(p,q)=>{const l=dist(p,q)||1;return{x:(q.x-p.x)/l,y:(q.y-p.y)/l};};
  const pathTick=(p,q,ratio=.5,size=7)=>{const u=unit(p,q),n={x:-u.y,y:u.x},m={x:p.x+(q.x-p.x)*ratio,y:p.y+(q.y-p.y)*ratio};return`M${(m.x-n.x*size).toFixed(1)} ${(m.y-n.y*size).toFixed(1)} L${(m.x+n.x*size).toFixed(1)} ${(m.y+n.y*size).toFixed(1)}`;};
  const setPoint=(name,p)=>{svg.querySelectorAll(`[data-point="${name}"]`).forEach(circle=>{circle.setAttribute('cx',p.x);circle.setAttribute('cy',p.y);});const handle=$one(`[data-handle="${name}"]`);if(handle)handle.setAttribute('transform',`translate(${p.x} ${p.y})`);const label=$one(`[data-label="${name}"]`),dx=name==='A'?-18:name==='B'?-15:name==='C'?12:10,dy=name==='A'||name==='D'?22:-15;label.setAttribute('x',p.x+dx);label.setAttribute('y',p.y+dy);};
  const setMarker=(name,d,show)=>{const el=$one(`[data-marker="${name}"]`);el.setAttribute('d',d||'');el.classList.toggle('hidden',!show);};
  function draw(){
    const B=points.B,D=points.D,C={x:B.x+D.x-A.x,y:B.y+D.y-A.y},v={x:B.x-A.x,y:B.y-A.y},w={x:D.x-A.x,y:D.y-A.y};
    const ab=Math.hypot(v.x,v.y),bc=Math.hypot(w.x,w.y),dot=v.x*w.x+v.y*w.y,cos=clamp(dot/(ab*bc||1),-1,1),angle=Math.acos(cos)*180/Math.PI;
    const ac=dist(A,C),bd=dist(B,D),d1={x:C.x-A.x,y:C.y-A.y},d2={x:D.x-B.x,y:D.y-B.y},diagCos=clamp(Math.abs((d1.x*d2.x+d1.y*d2.y)/(ac*bd||1)),0,1),diagAngle=Math.acos(diagCos)*180/Math.PI;
    const right=Math.abs(angle-90)<=.05,equalSides=Math.abs(ab-bc)<=.05,equalDiag=Math.abs(ac-bd)<=.05,perpDiag=Math.abs(diagAngle-90)<=.05;
    shape.setAttribute('d',`M${A.x} ${A.y} L${B.x} ${B.y} L${C.x} ${C.y} L${D.x} ${D.y} Z`);setPoint('A',A);setPoint('B',B);setPoint('C',C);setPoint('D',D);
    const lineAC=$one('[data-line="AC"]'),lineBD=$one('[data-line="BD"]');lineAC.setAttribute('d',`M${A.x} ${A.y} L${C.x} ${C.y}`);lineBD.setAttribute('d',`M${B.x} ${B.y} L${D.x} ${D.y}`);lineAC.classList.toggle('hidden',!diagonals);lineBD.classList.toggle('hidden',!diagonals);
    const ub=unit(A,B),ud=unit(A,D),s=18,p1={x:A.x+ub.x*s,y:A.y+ub.y*s},p3={x:A.x+ud.x*s,y:A.y+ud.y*s},p2={x:p1.x+ud.x*s,y:p1.y+ud.y*s};setMarker('rightA',`M${p1.x} ${p1.y} L${p2.x} ${p2.y} L${p3.x} ${p3.y}`,right&&['right','squareMarks'].includes(target));
    setMarker('sideAB',pathTick(A,B),equalSides&&['adjacentEqual','squareMarks'].includes(target));setMarker('sideBC',pathTick(B,C),equalSides&&['adjacentEqual','squareMarks'].includes(target));
    setMarker('diagAC',pathTick(A,C,.3),equalDiag&&['equalDiag','squareDiag'].includes(target));setMarker('diagBD',pathTick(B,D,.3),equalDiag&&['equalDiag','squareDiag'].includes(target));
    const O={x:(A.x+C.x)/2,y:(A.y+C.y)/2},u1=unit(O,C),u2=unit(O,D),r=12,o1={x:O.x+u1.x*r,y:O.y+u1.y*r},o3={x:O.x+u2.x*r,y:O.y+u2.y*r},o2={x:o1.x+u2.x*r,y:o1.y+u2.y*r};setMarker('rightO',`M${o1.x} ${o1.y} L${o2.x} ${o2.y} L${o3.x} ${o3.y}`,perpDiag&&['perpDiag','squareDiag'].includes(target));
    let ready=false,reading='';if(target==='right'){ready=right;reading=`∠DAB=${angle.toFixed(0)}°`;}if(target==='adjacentEqual'){ready=equalSides;reading=`AB=${ab.toFixed(0)}　BC=${bc.toFixed(0)}`;}if(target==='equalDiag'){ready=equalDiag;reading=`AC=${ac.toFixed(1)}　BD=${bd.toFixed(1)}`;}if(target==='perpDiag'){ready=perpDiag;reading=`対角線の交わる角=${diagAngle.toFixed(0)}°`;}if(target==='squareMarks'){ready=right&&equalSides;reading=`∠DAB=${angle.toFixed(0)}°　AB=${ab.toFixed(0)}　BC=${bc.toFixed(0)}`;}if(target==='squareDiag'){ready=equalDiag&&perpDiag;reading=`AC=${ac.toFixed(1)}　BD=${bd.toFixed(1)}　交角=${diagAngle.toFixed(0)}°`;}
    question.interactionReady=ready;root.classList.toggle('shape-ready',ready);document.querySelectorAll('#choices .choice').forEach(button=>{button.disabled=!ready;});readout.textContent=reading;status.textContent=ready?'✓ 条件成立！ 四角形を選ぼう':boundaryHit?'ここが動かせる端だよ。別の方向へ動かそう':'頂点を動かして条件に近づけよう';
  }
  const vectorFacts=()=>{const v={x:points.B.x-A.x,y:points.B.y-A.y},w={x:points.D.x-A.x,y:points.D.y-A.y},lv=Math.hypot(v.x,v.y)||1,lw=Math.hypot(w.x,w.y)||1,tv=Math.atan2(v.y,v.x),tw=Math.atan2(w.y,w.x);let diff=tv-tw;while(diff>Math.PI)diff-=Math.PI*2;while(diff<-Math.PI)diff+=Math.PI*2;return{v,w,lv,lw,tv,tw,sign:diff>=0?1:-1,angle:Math.acos(clamp((v.x*w.x+v.y*w.y)/(lv*lw),-1,1))*180/Math.PI};};
  function applyConstraints(activeVertex='B'){let f=vectorFacts(),desired=locks.angle?locks.angleValue:Math.round(f.angle),rad=desired*Math.PI/180;if(locks.angle&&locks.length){if(activeVertex==='D'){const thetaD=Math.atan2(points.D.y-A.y,points.D.x-A.x),thetaB=thetaD+locks.angleSign*rad;points.D={x:A.x+Math.cos(thetaD)*locks.bc,y:A.y+Math.sin(thetaD)*locks.bc};points.B={x:A.x+Math.cos(thetaB)*locks.ab,y:A.y+Math.sin(thetaB)*locks.ab};}else{const thetaB=Math.atan2(points.B.y-A.y,points.B.x-A.x),thetaD=thetaB-locks.angleSign*rad;points.B={x:A.x+Math.cos(thetaB)*locks.ab,y:A.y+Math.sin(thetaB)*locks.ab};points.D={x:A.x+Math.cos(thetaD)*locks.bc,y:A.y+Math.sin(thetaD)*locks.bc};}return;}if(activeVertex==='D'){const theta=f.tv-f.sign*rad,length=locks.length?locks.bc:Math.round(f.lw);points.D={x:A.x+Math.cos(theta)*length,y:A.y+Math.sin(theta)*length};}else{const theta=f.tw+f.sign*rad,length=locks.length?locks.ab:Math.round(f.lv);points.B={x:A.x+Math.cos(theta)*length,y:A.y+Math.sin(theta)*length};}if(locks.length){f=vectorFacts();points.B={x:A.x+f.v.x/f.lv*locks.ab,y:A.y+f.v.y/f.lv*locks.ab};points.D={x:A.x+f.w.x/f.lw*locks.bc,y:A.y+f.w.y/f.lw*locks.bc};}}
  const eventPoint=e=>{const pt=svg.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;return pt.matrixTransform(svg.getScreenCTM().inverse());};
  const movementBounds=name=>{const pad=3;if(locks.angle&&locks.length)return{minX:vertexBox.minX+pad,maxX:vertexBox.maxX-pad,minY:vertexBox.minY+pad,maxY:vertexBox.maxY-pad};const other=name==='B'?points.D:points.B;return{minX:Math.max(vertexBox.minX,derivedBox.minX-other.x+A.x)+pad,maxX:Math.min(vertexBox.maxX,derivedBox.maxX-other.x+A.x)-pad,minY:Math.max(vertexBox.minY,derivedBox.minY-other.y+A.y)+pad,maxY:Math.min(vertexBox.maxY,derivedBox.maxY-other.y+A.y)-pad};};
  const keepAway=(name,p)=>{const d=dist(A,p);if(d>=80)return p;const old=points[name],fallback=unit(A,d>1?p:old);return{x:A.x+fallback.x*80,y:A.y+fallback.y*80};};
  const down=e=>{if(stopped)return;const handle=e.target.closest('[data-handle]');if(!handle||!svg.contains(handle))return;active=handle.dataset.handle;activeId=e.pointerId;boundaryHit=false;svg.classList.add('is-dragging');status.textContent=`頂点${active}を動かしています`;try{svg.setPointerCapture(e.pointerId);}catch(_){}e.preventDefault();};
  const move=e=>{if(stopped||!active||e.pointerId!==activeId)return;const raw=eventPoint(e),bounds=movementBounds(active),limited={x:clamp(raw.x,bounds.minX,bounds.maxX),y:clamp(raw.y,bounds.minY,bounds.maxY)};boundaryHit=Math.abs(raw.x-limited.x)>.5||Math.abs(raw.y-limited.y)>.5;const next=keepAway(active,limited),before={B:{...points.B},D:{...points.D}};points[active]=next;applyConstraints(active);const C={x:points.B.x+points.D.x-A.x,y:points.B.y+points.D.y-A.y},outside=points.B.x<vertexBox.minX||points.B.x>vertexBox.maxX||points.B.y<vertexBox.minY||points.B.y>vertexBox.maxY||points.D.x<vertexBox.minX||points.D.x>vertexBox.maxX||points.D.y<vertexBox.minY||points.D.y>vertexBox.maxY||C.x<derivedBox.minX||C.x>derivedBox.maxX||C.y<derivedBox.minY||C.y>derivedBox.maxY;if(outside){points.B=before.B;points.D=before.D;boundaryHit=true;}draw();};
  const up=e=>{if(e.pointerId===activeId){try{if(svg.hasPointerCapture(e.pointerId))svg.releasePointerCapture(e.pointerId);}catch(_){}active=null;activeId=null;svg.classList.remove('is-dragging');draw();}};
  const updateLockLabels=()=>{const angleButton=root.querySelector('[data-lock="angle"]'),lengthButton=root.querySelector('[data-lock="length"]');angleButton.textContent=locks.angle?`🔒 ${locks.angleValue}°で角度ロック`:'🔓 角度をロック';lengthButton.textContent=locks.length?`🔒 AB=${locks.ab}・BC=${locks.bc}`:'🔓 長さをロック';};
  const toggleLock=e=>{if(stopped)return;const id=e.currentTarget.dataset.lock;if(id==='angle'){locks.angle=!locks.angle;if(locks.angle){const f=vectorFacts();locks.angleValue=Math.round(f.angle);locks.angleSign=f.sign;}}else{locks.length=!locks.length;if(locks.length){const f=vectorFacts();locks.ab=Math.round(f.lv);locks.bc=Math.round(f.lw);applyConstraints('B');}}e.currentTarget.classList.toggle('active',locks[id]);e.currentTarget.setAttribute('aria-pressed',String(locks[id]));updateLockLabels();draw();};
  const lockButtons=[...root.querySelectorAll('[data-lock]')];svg.addEventListener('pointerdown',down);lockButtons.forEach(b=>b.addEventListener('click',toggleLock));window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);window.addEventListener('pointercancel',up);applyConstraints('B');applyConstraints('D');updateLockLabels();draw();
  return()=>{stopped=true;root.classList.add('interaction-locked');svg.removeEventListener('pointerdown',down);lockButtons.forEach(b=>b.removeEventListener('click',toggleLock));window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);window.removeEventListener('pointercancel',up);};
}
function specialPoints(special){
  if(special==='right')return {A:{x:75,y:225},B:{x:75,y:70},C:{x:365,y:70},D:{x:365,y:225}};
  if(special==='equalDiag')return {A:{x:75,y:225},B:{x:75,y:70},C:{x:365,y:70},D:{x:365,y:225}};
  if(special==='adjacentEqual'||special==='perpDiag')return {A:{x:70,y:150},B:{x:220,y:65},C:{x:370,y:150},D:{x:220,y:235}};
  if(special==='squareMarks'||special==='squareDiag')return {A:{x:105,y:225},B:{x:105,y:75},C:{x:255,y:75},D:{x:255,y:225}};
  return POINTS;
}
function vertices(p=POINTS){return `<path class="l" d="M${p.A.x} ${p.A.y} L${p.B.x} ${p.B.y} L${p.C.x} ${p.C.y} L${p.D.x} ${p.D.y} Z"/><text class="v" x="${p.A.x-17}" y="${p.A.y+19}">A</text><text class="v" x="${p.B.x-13}" y="${p.B.y-13}">B</text><text class="v" x="${p.C.x+7}" y="${p.C.y-13}">C</text><text class="v" x="${p.D.x+5}" y="${p.D.y+19}">D</text>`;}
function diagonals(p){return `<path class="d" d="M${p.A.x} ${p.A.y} L${p.C.x} ${p.C.y} M${p.B.x} ${p.B.y} L${p.D.x} ${p.D.y}"/>`;}
function specialTick(p,from,to,ratio=.5){const a=p[from],b=p[to],mx=a.x+(b.x-a.x)*ratio,my=a.y+(b.y-a.y)*ratio,dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len;return `<path class="special-mark" d="M${(mx-nx*7).toFixed(1)} ${(my-ny*7).toFixed(1)} L${(mx+nx*7).toFixed(1)} ${(my+ny*7).toFixed(1)}"/>`;}
function diagonalGuide(points,segment,label,tone,offset){const o={x:220,y:147.5},ends={AO:[points.A,o],OC:[o,points.C],AC:[points.A,points.C],BO:[points.B,o],OD:[o,points.D],BD:[points.B,points.D]}[segment];const [a,b]=ends,dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1,n={x:-dy/len,y:dx/len},mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2},bend={x:mid.x+n.x*offset,y:mid.y+n.y*offset},text={x:mid.x+n.x*(offset+(offset>0?17:-17)),y:mid.y+n.y*(offset+(offset>0?17:-17))};return `<path class="length-${tone}" d="M${a.x.toFixed(1)} ${a.y.toFixed(1)} Q${bend.x.toFixed(1)} ${bend.y.toFixed(1)} ${b.x.toFixed(1)} ${b.y.toFixed(1)}"/><text class="length-${tone}-text" x="${text.x.toFixed(1)}" y="${text.y.toFixed(1)}">${label}</text>`;}
function parallelogram(fig){const p=specialPoints(fig.special);let svg=vertices(p);if(fig.side){const s=fig.side;svg+=sideArc(s.known,`${s.known}=${s.value}cm`,'known')+sideArc(s.ask,`${s.ask}=x`,'ask');}if(fig.angle){const a=fig.angle,known=a.knownVertex||a.known.slice(-1),ask=a.askVertex||a.ask.slice(-1),near={A:['D','B'],B:['A','C'],C:['B','D'],D:['C','A']};svg+=angleMark(known,...near[known],`${a.known}=${a.value}°`,'known')+angleMark(ask,...near[ask],`${a.ask}=x`,'ask');}if(fig.diagonal){const d=fig.diagonal,ac=d.name==='AC';svg+=ac?`<path class="d" d="M75 225 L365 70"/>`:`<path class="d" d="M145 70 L295 225"/>`;svg+=diagonalGuide(POINTS,d.known,`${d.known}=${d.value}cm`,'known',-18)+diagonalGuide(POINTS,d.ask,`${d.ask}=x`,'ask',18)+`<circle cx="220" cy="147" r="5" fill="#24324a"/><text class="v" x="229" y="166">O</text>`;}if(fig.special){const cx=(p.A.x+p.C.x)/2,cy=(p.A.y+p.C.y)/2;if(['right','squareMarks'].includes(fig.special))svg+=`<path class="special-mark" d="M${p.A.x} ${p.A.y-18} L${p.A.x+18} ${p.A.y-18} L${p.A.x+18} ${p.A.y}"/>`;if(['adjacentEqual','squareMarks'].includes(fig.special))svg+=specialTick(p,'A','B')+specialTick(p,'B','C');if(['equalDiag','squareDiag'].includes(fig.special))svg+=diagonals(p)+specialTick(p,'A','C',.28)+specialTick(p,'B','D',.28);if(['perpDiag','squareDiag'].includes(fig.special))svg+=fig.special==='squareDiag'?`<path class="special-mark" d="M${cx} ${cy} L${cx+9} ${cy-9} L${cx+18} ${cy} L${cx+9} ${cy+9} Z"/>`:`<path class="special-mark" d="M${cx} ${cy+13} L${cx+13} ${cy+13} L${cx+13} ${cy}"/>`;}return svg;}
function genericVertices(){return `<path class="l" d="M75 225 L145 70 L365 70 L295 225 Z"/><text class="v" x="58" y="244">A</text><text class="v" x="132" y="57">B</text><text class="v" x="372" y="57">C</text><text class="v" x="300" y="244">D</text>`;}
function generic(criterion){let svg=genericVertices();if(criterion==='p')svg+=parallel('AB')+parallel('DC')+parallel('AD',2)+parallel('BC',2);if(criterion==='s')svg+=tick('AB')+tick('DC')+tick('AD',2)+tick('BC',2);if(criterion==='ps')svg+=parallel('AB')+parallel('DC')+tick('AB',1,'blue',.74)+tick('DC',1,'blue',.74);if(criterion==='d'){const o=diagonalCenter(GENERIC);svg+=genericDiagonals()+`<circle cx="${o.x}" cy="${o.y}" r="4" fill="#24324a"/><text class="v" x="${o.x+9}" y="${o.y+18}">O</text>`+segmentTick(GENERIC,'A','C',.25)+segmentTick(GENERIC,'A','C',.75)+segmentTick(GENERIC,'B','D',.25,2)+segmentTick(GENERIC,'B','D',.75,2);}if(criterion==='a')svg+=genericAngle('A','D','B',1)+genericAngle('C','B','D',1)+genericAngle('B','A','C',2)+genericAngle('D','C','A',2);if(criterion==='bad-sides')svg+=tick('AB')+tick('BC')+tick('DC');if(criterion==='bad-parallel')svg+=parallel('AB')+parallel('DC');if(criterion==='bad-equaldiag')svg+=genericDiagonals()+segmentTick(GENERIC,'A','C',.32)+segmentTick(GENERIC,'B','D',.32);if(criterion==='bad-perp')svg+=genericDiagonals()+rightAngleAtDiagonalCenter(GENERIC);return svg;}
