'use strict';
(()=>{
const $=id=>document.getElementById(id),KEY='oniripi_heikoshihenkei_master_v1',mem={};
const store={get:k=>{try{return localStorage.getItem(k)}catch(e){return mem[k]||null}},set:(k,v)=>{try{localStorage.setItem(k,v)}catch(e){mem[k]=v}},del:k=>{try{localStorage.removeItem(k)}catch(e){delete mem[k]}}};
const data=()=>{try{return JSON.parse(store.get(KEY))||{high:0,history:[]}}catch(e){return{high:0,history:[]}}};
let level=1,session=[],idx=0,score=0,results=[],hintStep=0,locked=false,selected=null,stage='answer';
function typeset(el){if(window.MathJax&&MathJax.typesetPromise)MathJax.typesetPromise(el?[el]:undefined).catch(()=>{});}
function show(name){['start','quiz','result'].forEach(x=>$(x+'-screen').classList.toggle('active',x===name));}
function history(){const d=data();$('high-score').textContent=d.high||0;$('history-list').innerHTML=d.history?.length?d.history.slice(-20).reverse().map(h=>`<div>${h.date}　Lv.${h.level}　<b>${h.score}/${h.total}</b>点</div>`).join(''):'まだ記録がないよ！';}
function start(reuse=false){if(!reuse)session=makeSession(level);idx=0;score=0;results=[];$('level-tag').textContent='Lv.'+level;show('quiz');load();}
function load(){locked=false;selected=null;hintStep=0;stage='answer';const q=session[idx];q.interactionReady=q.type!=='E';$('counter').textContent=`Q ${idx+1} / ${session.length}`;$('progress-fill').style.width=`${idx/session.length*100}%`;$('score').textContent=score+'点';$('question-kind').textContent={A:'タイプA｜対辺',B:'タイプB｜対角・隣角',C:'タイプC｜対角線',D:'タイプD｜なるための条件',E:'タイプE｜特別な平行四辺形'}[q.type];$('question-text').innerHTML=q.text;$('question-note').textContent=q.type==='D'?'図の印と問題文で与えられた情報だけを使おう。':'';$('diagram').classList.remove('interaction-locked','shape-ready');$('diagram').innerHTML=renderDiagram(q.fig);$('feedback').className='feedback hidden';$('response-row').classList.remove('has-feedback');$('hint-list').innerHTML='';$('hint-warning').classList.add('hidden');$('hint-btn').disabled=false;$('hint-btn').textContent='💡 ヒント';$('submit-btn').classList.remove('hidden');$('next-btn').classList.add('hidden');buildAnswer(q);if(q.type==='E')q._cleanup=initSpecialInteraction(q,$('diagram'));typeset($('quiz-screen'));setTimeout(()=>{const f=$('answer');if(f)f.focus()},50);}
function buildAnswer(q){const box=$('answer-card');box.className='answer-card'+(q.type==='E'?' compact-choices':'');box.innerHTML='';if(q.kind==='number'){box.innerHTML=`<div class="answer-line"><span>答え =</span><span class="math-wrap"><math-field id="answer" virtual-keyboard-mode="off"></math-field></span><span>${q.unit||''}</span></div><p>※半角数字で入力してね。</p>`;const f=$('answer');f.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();submit()}});forceHalf(f);return;}if(q.kind==='choice'){box.innerHTML='<p class="choice-title">答えを選ぼう</p><div id="choices" class="choice-grid"></div>';choices(q.choices,q.answer);return;}renderJudge(q);}
function renderJudge(q){const box=$('answer-card');box.innerHTML=stage==='answer'?'<p class="choice-title">1 / 2　平行四辺形になるといえる？</p><div id="choices" class="choice-grid"></div>':'<p class="choice-title">2 / 2　根拠となる条件を選ぼう</p><div id="choices" class="choice-grid wide"></div>';if(stage==='answer')choices(['なる','ならない'],null);else choices(Q.criterion.map(c=>c.label),null);}
function choices(items){const root=$('choices');shuffle(items).forEach(item=>{const b=document.createElement('button');b.className='choice';b.textContent=item;b.setAttribute('aria-pressed','false');b.onclick=()=>{if(locked)return;selected=item;root.querySelectorAll('.choice').forEach(x=>{x.classList.remove('selected');x.setAttribute('aria-pressed','false');});b.classList.add('selected');b.setAttribute('aria-pressed','true');};root.appendChild(b);});}
function forceHalf(f){f.setAttribute('inputmode','latin');f.addEventListener('compositionend',e=>{if(e.data){const t=e.data.replace(/[０-９]/g,s=>String.fromCharCode(s.charCodeAt(0)-0xfee0));f.value='';f.insert(t);}});}
function intVal(){const f=$('answer');if(!f)return null;let s=(f.getValue?f.getValue('latex'):f.value)||'';s=s.replace(/\\[a-z]+|[{}\\s°]/g,'').replace(/[０-９]/g,c=>String.fromCharCode(c.charCodeAt(0)-0xfee0));return /^\d+$/.test(s)?Number(s):null;}
function submit(){if(locked)return;const q=session[idx];if(q.kind==='number'){const v=intVal();if(v===null)return note('答えを数字で入力してね。');finish(v===q.answer,String(v),false);return;}if(q.kind==='choice'){if(q.type==='E'&&!q.interactionReady)return note('先に頂点B・Dを動かして、条件を成立させよう。');if(!selected)return note('選択肢を1つ選んでね。');finish(selected===q.answer,selected,false);return;}if(stage==='answer'){if(!selected)return note('「なる」か「ならない」を選んでね。');if((selected==='なる')!==q.answer.yes){finish(false,selected,false);return;}if(!q.answer.yes){finish(true,selected,false);return;}stage='criterion';selected=null;renderJudge(q);return;}if(!selected)return note('根拠となる条件を選んでね。');const correct=Q.criterion.find(c=>c.id===q.answer.criterion).label;finish(selected===correct,`なる／${selected}`,false);}
function note(t){const f=$('feedback');f.className='feedback ng';f.textContent=t;f.classList.remove('hidden');setTimeout(()=>{if(!locked)f.className='feedback hidden'},1300);}
function finish(ok,val,gave){locked=true;const q=session[idx];if(q._cleanup){q._cleanup();q._cleanup=null;}if(ok)score+=10;$('score').textContent=score+'点';results.push({q,ok,val:gave?null:val});document.querySelectorAll('.choice').forEach(b=>b.disabled=true);const f=$('answer');if(f)f.disabled=true;const fb=$('feedback');fb.className='feedback '+(ok?'ok':gave?'giveup':'ng');const ans=q.kind==='judge'?(q.answer.yes?`なる／${Q.criterion.find(c=>c.id===q.answer.criterion).label}`:'ならない'):q.answer+(q.unit||'');fb.innerHTML=`${ok?'⭕ 正解！':`❌ ${gave?'ギブアップ':'おしい！'}`}<br><span>あなたの答え：${val||'なし'}</span><br><span>正しい答え：<b>${ans}</b></span><br><span>${ok?q.solution:q.wrong(val)}</span>`;fb.classList.remove('hidden');$('response-row').classList.add('has-feedback');$('submit-btn').classList.add('hidden');$('hint-btn').disabled=true;$('next-btn').classList.remove('hidden');if(ok)try{confetti({particleCount:55,spread:60,origin:{y:.7}})}catch(e){}typeset(fb);}
async function hint(){if(locked)return;const q=session[idx];if(hintStep===q.hints.length-1){if(!confirm('次のヒントは答えだよ！見ると不正解で確定します。'))return;$('hint-list').insertAdjacentHTML('beforeend',`<div class="hint-item answer"><b>答え</b><br>${q.hints[hintStep]}</div>`);finish(false,null,true);return;}$('hint-list').insertAdjacentHTML('beforeend',`<div class="hint-item"><b>ステップ${hintStep+1}</b><br>${q.hints[hintStep++]}</div>`);if(hintStep===q.hints.length-1){$('hint-warning').classList.remove('hidden');$('hint-btn').textContent='⚠️ 答えを見る';}typeset($('hint-list'));}
function next(){idx++;if(idx>=session.length)return result();load();}
function result(){show('result');$('result-score').textContent=`${score} / ${session.length*10} 点`;$('result-message').textContent=score>=session.length*8?'🏆 クリア！平行四辺形マスター！':'📘 まちがいを復習して、もう一度挑戦しよう！';const d=data();d.high=Math.max(d.high||0,score);d.history=d.history||[];d.history.push({date:new Date().toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}),score,total:session.length*10,level});d.history=d.history.slice(-20);store.set(KEY,JSON.stringify(d));$('review-list').innerHTML=results.map((r,i)=>`<div class="review-item">${r.ok?'⭕':'❌'} 第${i+1}問：${r.q.type}　あなた：${r.val||'なし'} ／ 正解：<b>${r.q.kind==='judge'?(r.q.answer.yes?'なる':'ならない'):r.q.answer+(r.q.unit||'')}</b></div>`).join('');$('wrong-btn').classList.toggle('hidden',!results.some(r=>!r.ok));if(score>=session.length*8)try{confetti({particleCount:180,spread:100,origin:{y:.6}})}catch(e){}}
document.querySelectorAll('.level').forEach(b=>b.onclick=()=>{document.querySelectorAll('.level').forEach(x=>x.classList.remove('active'));b.classList.add('active');level=+b.dataset.level;});$('start-btn').onclick=()=>start();$('retry-btn').onclick=()=>start();$('wrong-btn').onclick=()=>{session=results.filter(r=>!r.ok).map(r=>r.q);idx=0;score=0;results=[];show('quiz');load();};$('home-btn').onclick=()=>{history();show('start')};$('quit-btn').onclick=()=>{if(confirm('ホームに戻る？ いまのチャレンジは記録されません。')){history();show('start');}};$('submit-btn').onclick=submit;$('next-btn').onclick=next;$('hint-btn').onclick=hint;$('reset-btn').onclick=()=>{if(confirm('学習履歴を消す？')){store.del(KEY);history();}};$('card-btn').onclick=()=>$('card-dialog').showModal();$('close-card').onclick=()=>$('card-dialog').close();history();
})();
